# Generated by Django 6.0.2 on 2026-02-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hotelTypes',
            fields=[
                ('hotel_id', models.AutoField(db_column='hotel_id', primary_key=True, serialize=False)),
                ('hotel_type', models.CharField(db_column='hotel_type', max_length=255)),
                ('hotel_img', models.BinaryField(db_column='hotel_img')),
            ],
            options={
                'db_table': 'hotel_type',
                'managed': True,
            },
        ),
    ]
