# Generated by Django 6.0.2 on 2026-02-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelBooking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoteltypes',
            name='hotel_img',
            field=models.ImageField(db_column='hotel_img', upload_to=''),
        ),
    ]
