# Generated by Django 6.0.2 on 2026-02-19 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelBooking', '0002_alter_hoteltypes_hotel_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('booking_id', models.AutoField(db_column='booking_id', primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='first_name', max_length=255)),
                ('last_name', models.CharField(db_column='last_name', max_length=255)),
                ('email', models.EmailField(db_column='email', max_length=254)),
                ('phone_number', models.CharField(db_column='phone_number', max_length=20)),
                ('check_in_date', models.DateField(db_column='check_in_date')),
                ('check_out_date', models.DateField(db_column='check_out_date')),
                ('hotel_type', models.ForeignKey(db_column='hotel_type', on_delete=django.db.models.deletion.CASCADE, to='hotelBooking.hoteltypes')),
            ],
            options={
                'db_table': 'booking',
                'managed': True,
            },
        ),
    ]
