# Generated by Django 6.0.2 on 2026-04-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelBooking', '0004_remove_booking_email_remove_booking_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(db_column='phone_number', max_length=20, null=True),
        ),
    ]
